config/routes.rb
SampleApp2::Application.routes.draw do
  resources :users do
   member do
    get :following, :followers
   end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :calendars, only: [:destroy, :create, :new, :update]
  resources :relationships, only: [:create, :destroy]
  root 'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/login', to: 'sessions#new', via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'delete'
  match '/users', to: 'users#index', via: 'get'
  match '/sample', to: 'static_pages#micropost', via: 'get'
  match '/calendar/:year/:month/:day', to: 'calendars#calendar', via: 'get'
  match '/edit/:year/:month/:day', to: 'calendars#edit', via: 'get'
  match '/index', to: 'calendars#index', via: 'get'
  post '/calendars/:date' => 'calendars#calendar'
  post "static_pages/show" => "static_pages#show"
  post '/calendar/:date' => 'calendars#update'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if signed_in?
      @labomem = User.all
      @laboratory = current_user.labo
      @calendar_all = Calendar.all
      @user = current_user
		  @micropost = current_user.microposts.build
      @calendar = current_user.calendars.build
      @feed_items = current_user.feed.paginate(page: params[:page])
      @today = Time.zone.now
      @year = @today.year
      if @today.month < 10
        @month = "0" + @today.month.to_s
      else
        @month = @today.month
      end

      if @today.day < 10
        @day = "0" + @today.day.to_s
      else
        @day = @today.day
      end
      @signed_in_user = current_user.id
      @button = current_user.microposts.build
	  end
  end


  def show
    render :text => "id = #{params[:id]}"
    render :text => " #{params[:title]}, #{params[:num]}"
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
	The <a href="http://railstutorial.jp/">Ruby on Rails Tutorial</a>
	is a project to make a book and screencasts to teach web development
	with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
	is the sample application for the tutorial.
</p>

app/views/static_pages/calendar.html.erb

<table border="0" cellpadding="2" cellspacing="1" bgcolor="#999999" width="100%">
<tr align="center" bgcolor="#FFFFFF">
<td colspan="7">2014年11月</td>
</tr>
<tr align="center" bgcolor="#C9DFE8">
<td>日</td>
<td>月</td>
<td>火</td>
<td>水</td>
<td>木</td>
<td>金</td>
<td>土</td>
</tr>
<tr align="center" bgcolor="#FFFFFF">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>1</td>
</tr>
<tr align="center" bgcolor="#FFFFFF">
<td bgcolor="#FF9999">2</td>
<td><%= link_to '3', '/calendar/2014/11/03' %></td>
<td>4</td>
<td>5</td>
<td>6</td>
<td>7</td>
<td>8</td>
</tr>
<tr align="center" bgcolor="#FFFFFF">
<td bgcolor="#FF9999">9</td>
<td>10</td>
<td>11</td>
<td>12</td>
<td>13</td>
<td>14</td>
<td>15</td>
</tr>
<tr align="center" bgcolor="#FFFFFF">
<td bgcolor="#FF9999">16</td>
<td>17</td>
<td>18</td>
<td>19</td>
<td>20</td>
<td>21</td>
<td>22</td>
</tr>
<tr align="center" bgcolor="#FFFFFF">
<td bgcolor="#FF9999">23</td>
<td>24</td>
<td>25</td>
<td>26</td>
<td>27</td>
<td>28</td>
<td>29</td>
</tr>
<tr align="center" bgcolor="#FFFFFF">
<td bgcolor="#FF9999">30</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</table>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
	Contact Ruby on Rails Tutorial about the sample app at the
	<a href="http://railstutorial.jp/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
	Get help on the Ruby on Rails Tutorial at the
	<a href="http://railstutorial.jp/help">Rails Tutorial help page</a>.
	To get help on this sample app, see the
	<a href="http://railstutorial.jp/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
	<% if @user.id == 1 or @user.id == 2 or @user.id == 3 or
		  @user.id == 4 or @user.id == 5 or @user.id == 6 or
		  @user.id == 7 or @user.id == 8 or @user.id == 9 or
		  @user.id == 10 %>
<%# 教員用のページを表示する %>

		<div class="row">
			<aside class="span3">
				<%# student_array = [] %>
				<% @labomem.where(:labo => @user.labo).each do |labo| %>
					<% unless labo.id == 1 or labo.id == 2 or labo.id == 3 or labo.id == 4 or 
							  labo.id == 5 or labo.id == 6 or labo.id == 7 or labo.id == 8 or
							  labo.id == 9 or labo.id == 10 %>
						<%= labo.student_id %>
						<%= link_to labo.name, controller: "static_pages", action: "home",labomem: labo.id %>
						<p></P>								
					<% end %>
				<% end %>
			</aside>
			<div class="span8">
			
			<% if params[:labomem] %> 
			<div id="sample">
				<% student = @labomem.find(params[:labomem]) %>
				<font size="5"><%= student.student_id %> <%= student.name %></font>
				<% sum = 0.0 %>
				<% array = [] %>
				<% @calendar_all.where(:user_id => params[:labomem]).find_each do |count| %>
				
					<% sum += count.time.to_f %>
					<% array << count.date[4,2] %>
				<% end %>
				<section>
					合計 <%= sum.floor %> 時間 <%= (number_with_precision(sum - sum.floor, :precision => 2).to_f * 300 / 5).round %> 分
				</section>
				<table><tr>
				<% array.uniq.each do |uniq| %>
				<td>
				<div id="sample3">
					
					<%= link_to "#{uniq} 月", controller: "static_pages", action: "home", month: uniq,labomem: params[:labomem] %>
				
				</div>
				</td>
				<% end %>
			</tr></table>
				
				<p></p>

				<% if params[:month] %>
				
					<% @calendar_all.where(:user_id => params[:labomem]).find_each do |calendar| %>
						<% unless calendar.time == nil && calendar.content == nil %>
							<% if calendar.date[4,2] == params[:month] %>
							
								<%= link_to calendar.date[6,2], controller: "calendars", action: "index",date: calendar.date,id: calendar.user_id %><%= " 日" %>
								<% unless calendar.time == nil %>
									<%= calendar.time.floor %><%= " 時間" %>
									<%= (number_with_precision(calendar.time - calendar.time.floor, :precision => 2).to_f * 300 / 5).round %><%= " 分" %>
								
									<p></p>
								<% else %>
									<%= "0 時間 0 分" %> 
								<% end %>
							<% end %>
						<% end %>
					<% end %>

				

				<% else %>

				
					<% @calendar_all.where(:user_id => params[:labomem]).find_each do |calendar| %>
						<% unless calendar.time == nil && calendar.content == nil %>
							<% if calendar.date[4,2] == @month.to_s %>
								<%= link_to calendar.date[6,2], controller: "calendars", action: "index",date: calendar.date,id: calendar.user_id %><%= " 日" %>
								<% unless calendar.time == nil %>
									<%= calendar.time.floor %><%= " 時間" %>
									<%= (number_with_precision(calendar.time - calendar.time.floor, :precision => 2).to_f * 300 / 5).round %><%= " 分" %>
								
									<p></p>
								<% else %>
									<%= "0 時間 0 分" %> 
								<% end %>
							<% end %>
						<% end %>
					<% end %>
				
				<% end %>
			<% else %>
			<div class="span8">
				<div id="sample">
				
					<h3><%= @laboratory %>のつぶやき</h3>

					<%= render 'shared/feed' %>
				</div>
			</div>
			<% end %>
		</div>
		</div>
		</div>
	<% else %>
<%# 学生用のページを表示する %>

	<div class="row">
		<aside class="span4">
			<section>
				<div class="row">
					<aside class="span4">
						<section>
							<%= render 'shared/user_info' %>
						</section>
						<section>
							<%= render 'shared/stats' %>
						</section>
						<section>
							<%= render 'shared/micropost_form' %>
						</section>

					</aside>
				</div>

			</section>
			<section>

				<% if params[:calendar] %>
					<%= render "shared/calendar_#{params[:calendar]}" %>
				<% else %>
					<%= render "shared/calendar_#{@year}#{@month}" %>
				<% end %>

			</section>
			<section>
				<%= link_to "本日の研究内容", "/calendar/#{@year}/#{@month}/#{@day}",
						class: "btn btn-large btn-primary" %>		
			</section>
		</aside>
		
		<div class="span8">
			<div id="sample">
			
			<h3><%= @laboratory %>のつぶやき</h3>

			<%= render 'shared/feed' %>
			</div>
		
		<div>
	</div>
	<% end %>


<% else %>
	<% provide(:title, "Sign in") %>

<%# ログインしていない場合 %>
<div class="row">
	<div class="span6 offset3">
		<div id="sample" >
		<%= form_for(:session, url: sessions_path) do |f| %>
			<h1>ログイン</h1>
			<%= f.label :"メール" %>
			<%= f.text_field :email %>
			<%= f.label :"パスワード" %>
			<%= f.password_field :password %>
			<%= f.submit "ログイン", class: "btn btn-large btn-primary" %>
		<% end %>
		<p><%= link_to "アカウント作成", signup_path %></p>
	</div>
</div>
</div>
<% end %>

app/views/static_pages/micropost.html.erb
<% if signed_in? %>
	<div class="row">
		<aside class="span4">
			<section>
				<%= render 'shared/user_info' %>
			</section>
			<section>
				<%= render 'shared/stats' %>
			</section>
			<section>
				<%= render 'shared/micropost_form' %>
			</section>
		</aside>
		<div class="span8">
			<h3>Micropost Feed</h3>
			<%= render 'shared/feed' %>
		</div>
	</div>
<% else %>
	<% provide(:title, "Sign in") %>
<h1>Sign in</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(:session, url: sessions_path) do |f| %>
			<%= f.label :email %>
			<%= f.text_field :email %>
			<%= f.label :password %>
			<%= f.password_field :password %>
			<%= f.submit "Sign in", class: "btn btn-large btn-primary" %>
		<% end %>
		<p>New user? <%= link_to "Sign up now!", signup_path %></p>
	</div>
</div>
<% end %>

app/views/static_pages/sample.html.erb
<% if signed_in? %>
	<div class="row">
		<aside class="span4">
			<section>
				<%= render 'shared/user_info' %>
			</section>
			<section>
				<%= render 'shared/stats' %>
			</section>
			<section>
				<%= render 'shared/micropost_form' %>
			</section>
		</aside>
		<div class="span8">
			<h3>Micropost Feed</h3>
			<%= render 'shared/feed' %>
		</div>
	</div>
<% else %>
	<% provide(:title, "Sign in") %>
<h1>Sign in</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(:session, url: sessions_path) do |f| %>
			<%= f.label :email %>
			<%= f.text_field :email %>
			<%= f.label :password %>
			<%= f.password_field :password %>
			<%= f.submit "Sign in", class: "btn btn-large btn-primary" %>
		<% end %>
		<p>New user? <%= link_to "Sign up now!", signup_path %></p>
	</div>
</div>
<% end %>