config/routes.rb
SampleApp2::Application.routes.draw do
  resources :users do
   member do
    get :following, :followers
   end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :calendars, only: [:destroy, :create, :new, :update]
  resources :relationships, only: [:create, :destroy]
  root 'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/login', to: 'sessions#new', via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'delete'
  match '/users', to: 'users#index', via: 'get'
  match '/sample', to: 'static_pages#micropost', via: 'get'
  match '/calendar/:year/:month/:day', to: 'calendars#calendar', via: 'get'
  match '/edit/:year/:month/:day', to: 'calendars#edit', via: 'get'
  match '/index', to: 'calendars#index', via: 'get'
  post '/calendars/:date' => 'calendars#calendar'
  post "static_pages/show" => "static_pages#show"
  post '/calendar/:date' => 'calendars#update'

end

app/views/shared/_calendar_201412.html.erb
<table border="0" cellpadding="2" cellspacing="1" bgcolor="#333333" width="100%">
<tr align="center" bgcolor="#FFFFFF">
<td colspan="7">2014年12月 <%= link_to ">>", controller: "static_pages", action: "home", calendar: "201501" %></td>
</tr>
<tr align="center" bgcolor="#CCCCCC">
<td>日</td>
<td>月</td>
<td>火</td>
<td>水</td>
<td>木</td>
<td>金</td>
<td>土</td>
</tr>
<tr align="center" bgcolor="#FFFFFF">
<td></td>
<td><%= link_to '1', "/calendar/2014/12/01" %></td>
<td><%= link_to '2', '/calendar/2014/12/02' %></td>
<td><%= link_to '3', '/calendar/2014/12/03' %></td>
<td><%= link_to '4', '/calendar/2014/12/04' %></td>
<td><%= link_to '5', '/calendar/2014/12/05' %></td>
<td><%= link_to '6', '/calendar/2014/12/06' %></td>
</tr>
<tr align="center" bgcolor="#FFFFFF">
<td><%= link_to '7', '/calendar/2014/12/07' %></td>
<td><%= link_to '8', '/calendar/2014/12/08' %></td>
<td><%= link_to '9', '/calendar/2014/12/09' %></td>
<td><%= link_to '10', '/calendar/2014/12/10' %></td>
<td><%= link_to '11', '/calendar/2014/12/11' %></td>
<td><%= link_to '12', '/calendar/2014/12/12' %></td>
<td><%= link_to '13', '/calendar/2014/12/13' %></td>
</tr>
<tr align="center" bgcolor="#FFFFFF">
<td><%= link_to '14', '/calendar/2014/12/14' %></td>
<td><%= link_to '15', '/calendar/2014/12/15' %></td>
<td><%= link_to '16', '/calendar/2014/12/16' %></td>
<td><%= link_to '17', '/calendar/2014/12/17' %></td>
<td><%= link_to '18', '/calendar/2014/12/18' %></td>
<td><%= link_to '19', '/calendar/2014/12/19' %></td>
<td><%= link_to '20', '/calendar/2014/12/20' %></td>
</tr>
<tr align="center" bgcolor="#FFFFFF">
<td><%= link_to '21', '/calendar/2014/12/21' %></td>
<td><%= link_to '22', '/calendar/2014/12/22' %></td>
<td><%= link_to '23', '/calendar/2014/12/23' %></td>
<td><%= link_to '24', '/calendar/2014/12/24' %></td>
<td><%= link_to '25', '/calendar/2014/12/25' %></td>
<td><%= link_to '26', '/calendar/2014/12/26' %></td>
<td><%= link_to '27', '/calendar/2014/12/27' %></td>
</tr>
<tr align="center" bgcolor="#FFFFFF">
<td><%= link_to '28', '/calendar/2014/12/28' %></td>
<td><%= link_to '29', '/calendar/2014/12/29' %></td>
<td><%= link_to '30', '/calendar/2014/12/30' %></td>
<td><%= link_to '31', '/calendar/2014/12/31' %></td>
<td></td>
<td></td>
<td></td>
</tr>
</table>

app/views/shared/_calendar_201501.html.erb
<table border="0" cellpadding="2" cellspacing="1" bgcolor="#333333" width="100%">
<tr align="center" bgcolor="#FFFFFF">
<td colspan="7"><%= link_to "<<", controller: "static_pages", action: "home", calendar: "201412" %> 2015年1月 <%= link_to ">>", controller: "static_pages", action: "home", calendar: "201502" %></td>
</tr>
<tr align="center" bgcolor="#CCCCCC">
<td>日</td>
<td>月</td>
<td>火</td>
<td>水</td>
<td>木</td>
<td>金</td>
<td>土</td>
</tr>
<tr align="center" bgcolor="#FFFFFF">
<td></td>
<td></td>
<td></td>
<td></td>
<td><%= link_to '1', "/calendar/2015/01/01" %></td>
<td><%= link_to '2', "/calendar/2015/01/02" %></td>
<td><%= link_to '3', "/calendar/2015/01/03" %></td>
</tr>
<tr align="center" bgcolor="#FFFFFF">
<td><%= link_to '4', "/calendar/2015/01/04" %></td>
<td><%= link_to '5', "/calendar/2015/01/05" %></td>
<td><%= link_to '6', "/calendar/2015/01/06" %></td>
<td><%= link_to '7', "/calendar/2015/01/07" %></td>
<td><%= link_to '8', "/calendar/2015/01/08" %></td>
<td><%= link_to '9', "/calendar/2015/01/09" %></td>
<td><%= link_to '10', "/calendar/2015/01/10" %></td>
</tr>
<tr align="center" bgcolor="#FFFFFF">
<td><%= link_to '11', "/calendar/2015/01/11" %></td>
<td><%= link_to '12', "/calendar/2015/01/12" %></td>
<td><%= link_to '13', "/calendar/2015/01/13" %></td>
<td><%= link_to '14', "/calendar/2015/01/14" %></td>
<td><%= link_to '15', "/calendar/2015/01/15" %></td>
<td><%= link_to '16', "/calendar/2015/01/16" %></td>
<td><%= link_to '17', "/calendar/2015/01/17" %></td>
</tr>
<tr align="center" bgcolor="#FFFFFF">
<td><%= link_to '18', "/calendar/2015/01/18" %></td>
<td><%= link_to '19', "/calendar/2015/01/19" %></td>
<td><%= link_to '20', "/calendar/2015/01/20" %></td>
<td><%= link_to '21', "/calendar/2015/01/21" %></td>
<td><%= link_to '22', "/calendar/2015/01/22" %></td>
<td><%= link_to '23', "/calendar/2015/01/23" %></td>
<td><%= link_to '24', "/calendar/2015/01/24" %></td>
</tr>
<tr align="center" bgcolor="#FFFFFF">
<td><%= link_to '25', "/calendar/2015/01/25" %></td>
<td><%= link_to '26', "/calendar/2015/01/26" %></td>
<td><%= link_to '27', "/calendar/2015/01/27" %></td>
<td><%= link_to '28', "/calendar/2015/01/28" %></td>
<td><%= link_to '29', "/calendar/2015/01/29" %></td>
<td><%= link_to '30', "/calendar/2015/01/30" %></td>
<td><%= link_to '31', "/calendar/2015/01/31" %></td>
</tr>
</table>


app/views/shared/_calendar_201502.html.erb
<table border="0" cellpadding="2" cellspacing="1" bgcolor="#333333" width="100%">
<tr align="center" bgcolor="#FFFFFF">
<td colspan="7"><%= link_to "<<", controller: "static_pages", action: "home", calendar: "201501" %> 2015年2月 <%= link_to ">>", controller: "static_pages", action: "home", calendar: "201503" %></td>
</tr>
<tr align="center" bgcolor="#CCCCCC">
<td>日</td>
<td>月</td>
<td>火</td>
<td>水</td>
<td>木</td>
<td>金</td>
<td>土</td>
</tr>
<tr align="center" bgcolor="#FFFFFF">
<td><%= link_to '1', "/calendar/2015/02/01" %></td>
<td><%= link_to '2', "/calendar/2015/02/02" %></td>
<td><%= link_to '3', "/calendar/2015/02/03" %></td>
<td><%= link_to '4', "/calendar/2015/02/04" %></td>
<td><%= link_to '5', "/calendar/2015/02/05" %></td>
<td><%= link_to '6', "/calendar/2015/02/06" %></td>
<td><%= link_to '7', "/calendar/2015/02/07" %></td>
</tr>
<tr align="center" bgcolor="#FFFFFF">
<td><%= link_to '8', "/calendar/2015/02/08" %></td>
<td><%= link_to '9', "/calendar/2015/02/09" %></td>
<td><%= link_to '10', "/calendar/2015/02/10" %></td>
<td><%= link_to '11', "/calendar/2015/02/11" %></td>
<td><%= link_to '12', "/calendar/2015/02/12" %></td>
<td><%= link_to '13', "/calendar/2015/02/13" %></td>
<td><%= link_to '14', "/calendar/2015/02/14" %></td>
</tr>
<tr align="center" bgcolor="#FFFFFF">
<td><%= link_to '15', "/calendar/2015/02/15" %></td>
<td><%= link_to '16', "/calendar/2015/02/16" %></td>
<td><%= link_to '17', "/calendar/2015/02/17" %></td>
<td><%= link_to '18', "/calendar/2015/02/18" %></td>
<td><%= link_to '19', "/calendar/2015/02/19" %></td>
<td><%= link_to '20', "/calendar/2015/02/20" %></td>
<td><%= link_to '21', "/calendar/2015/02/21" %></td>
</tr>
<tr align="center" bgcolor="#FFFFFF">
<td><%= link_to '22', "/calendar/2015/02/22" %></td>
<td><%= link_to '23', "/calendar/2015/02/23" %></td>
<td><%= link_to '24', "/calendar/2015/02/24" %></td>
<td><%= link_to '25', "/calendar/2015/02/25" %></td>
<td><%= link_to '26', "/calendar/2015/02/26" %></td>
<td><%= link_to '27', "/calendar/2015/02/27" %></td>
<td><%= link_to '28', "/calendar/2015/02/28" %></td>
</tr>
</table>


app/views/shared/_calendar_201503.html.erb
<table border="0" cellpadding="2" cellspacing="1" bgcolor="#333333" width="100%">
<tr align="center" bgcolor="#FFFFFF">
<td colspan="7"><%= link_to "<<", controller: "static_pages", action: "home", calendar: "201502" %>2015年3月<%= link_to ">>", controller: "static_pages", action: "home", calendar: "201504" %></td>
</tr>
<tr align="center" bgcolor="#CCCCCC">
<td>日</td>
<td>月</td>
<td>火</td>
<td>水</td>
<td>木</td>
<td>金</td>
<td>土</td>
</tr>
<tr align="center" bgcolor="#FFFFFF">
<td><%= link_to '1', "/calendar/2015/03/01" %></td>
<td><%= link_to '2', "/calendar/2015/03/02" %></td>
<td><%= link_to '3', "/calendar/2015/03/03" %></td>
<td><%= link_to '4', "/calendar/2015/03/04" %></td>
<td><%= link_to '5', "/calendar/2015/03/05" %></td>
<td><%= link_to '6', "/calendar/2015/03/06" %></td>
<td><%= link_to '7', "/calendar/2015/03/07" %></td>
</tr>
<tr align="center" bgcolor="#FFFFFF">
<td><%= link_to '8', "/calendar/2015/03/08" %></td>
<td><%= link_to '9', "/calendar/2015/03/09" %></td>
<td><%= link_to '10', "/calendar/2015/03/10" %></td>
<td><%= link_to '11', "/calendar/2015/03/11" %></td>
<td><%= link_to '12', "/calendar/2015/03/12" %></td>
<td><%= link_to '13', "/calendar/2015/03/13" %></td>
<td><%= link_to '14', "/calendar/2015/03/14" %></td>
</tr>
<tr align="center" bgcolor="#FFFFFF">
<td><%= link_to '15', "/calendar/2015/03/15" %></td>
<td><%= link_to '16', "/calendar/2015/03/16" %></td>
<td><%= link_to '17', "/calendar/2015/03/17" %></td>
<td><%= link_to '18', "/calendar/2015/03/18" %></td>
<td><%= link_to '19', "/calendar/2015/03/19" %></td>
<td><%= link_to '20', "/calendar/2015/03/20" %></td>
<td><%= link_to '21', "/calendar/2015/03/21" %></td>
</tr>
<tr align="center" bgcolor="#FFFFFF">
<td><%= link_to '22', "/calendar/2015/03/22" %></td>
<td><%= link_to '23', "/calendar/2015/03/23" %></td>
<td><%= link_to '24', "/calendar/2015/03/24" %></td>
<td><%= link_to '25', "/calendar/2015/03/25" %></td>
<td><%= link_to '26', "/calendar/2015/03/26" %></td>
<td><%= link_to '27', "/calendar/2015/03/27" %></td>
<td><%= link_to '28', "/calendar/2015/03/28" %></td>
</tr>
<tr align="center" bgcolor="#FFFFFF">
<td><%= link_to '29', "/calendar/2015/03/29" %></td>
<td><%= link_to '30', "/calendar/2015/03/30" %></td>
<td><%= link_to '31', "/calendar/2015/03/31" %></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</table>

app/views/shared/_calendar_201504.html.erb
<table border="0" cellpadding="2" cellspacing="1" bgcolor="#333333" width="100%">
<tr align="center" bgcolor="#FFFFFF">
<td colspan="7"><%= link_to "<<", controller: "static_pages", action: "home", calendar: "201503" %>2015年4月</td>
</tr>
<tr align="center" bgcolor="#CCCCCC">
<td>日</td>
<td>月</td>
<td>火</td>
<td>水</td>
<td>木</td>
<td>金</td>
<td>土</td>
</tr>
<tr align="center" bgcolor="#FFFFFF">
<td></td>
<td></td>
<td></td>
<td><%= link_to '1', "/calendar/2015/04/01" %></td>
<td><%= link_to '2', "/calendar/2015/04/02" %></td>
<td><%= link_to '3', "/calendar/2015/04/03" %></td>
<td><%= link_to '4', "/calendar/2015/04/04" %></td>
</tr>
<tr align="center" bgcolor="#FFFFFF">
<td><%= link_to '5', "/calendar/2015/04/05" %></td>
<td><%= link_to '6', "/calendar/2015/04/06" %></td>
<td><%= link_to '7', "/calendar/2015/04/07" %></td>
<td><%= link_to '8', "/calendar/2015/04/08" %></td>
<td><%= link_to '9', "/calendar/2015/04/09" %></td>
<td><%= link_to '10', "/calendar/2015/04/10" %></td>
<td><%= link_to '11', "/calendar/2015/04/11" %></td>
</tr>
<tr align="center" bgcolor="#FFFFFF">
<td><%= link_to '12', "/calendar/2015/04/12" %></td>
<td><%= link_to '13', "/calendar/2015/04/13" %></td>
<td><%= link_to '14', "/calendar/2015/04/14" %></td>
<td><%= link_to '15', "/calendar/2015/04/15" %></td>
<td><%= link_to '16', "/calendar/2015/04/16" %></td>
<td><%= link_to '17', "/calendar/2015/04/17" %></td>
<td><%= link_to '18', "/calendar/2015/04/18" %></td>
</tr>
<tr align="center" bgcolor="#FFFFFF">
<td><%= link_to '19', "/calendar/2015/04/19" %></td>
<td><%= link_to '20', "/calendar/2015/04/20" %></td>
<td><%= link_to '21', "/calendar/2015/04/21" %></td>
<td><%= link_to '22', "/calendar/2015/04/22" %></td>
<td><%= link_to '23', "/calendar/2015/04/23" %></td>
<td><%= link_to '24', "/calendar/2015/04/24" %></td>
<td><%= link_to '25', "/calendar/2015/04/25" %></td>
</tr>
<tr align="center" bgcolor="#FFFFFF">
<td><%= link_to '26', "/calendar/2015/04/26" %></td>
<td><%= link_to '27', "/calendar/2015/04/27" %></td>
<td><%= link_to '28', "/calendar/2015/04/28" %></td>
<td><%= link_to '29', "/calendar/2015/04/29" %></td>
<td><%= link_to '30', "/calendar/2015/04/30" %></td>
<td></td>
<td></td>
</tr>
</table>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(object.errors.count, "error") %>.
		</div>
		<ul>
		<% object.errors.full_messages.each do |msg| %>
			<li>* <%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol class="microposts">
		<%= render partial: 'shared/feed_item', collection: @feed_items %>
	</ol>
	<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
	<%= link_to gravatar_for(feed_item.user), feed_item.user %>
		<span class="user">
			<%= link_to feed_item.user.name, feed_item.user %>
		</span>
		<span class="content"><%= feed_item.content %></span>
		<span class="timestamp">
			Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
		</span>
	<% if current_user?(feed_item.user) %>
		<% unless feed_item.content == "start" || feed_item.content == "stop" %>
			<%= link_to "delete", feed_item, method: :delete,
											data: { confirm: "You sure?" },
											title: feed_item.content %>
		<% end %>
	<% end %>


</li>

app/views/shared/_feed_itemc.html.erb
<li id="<%= feed_itemc.id %>">
	<%= link_to gravatar_for(feed_itemc.user), feed_itemc.user %>
		<span class="user">
			<%= link_to feed_itemc.user.name, feed_itemc.user %>
		</span>
		<span class="content"><%= feed_itemc.content %></span>
		
		<span class="timestamp">
			Posted <%= time_ago_in_words(feed_itemc.created_at) %> ago.
		</span>
	<% if current_user?(feed_itemc.user) %>
		<%= link_to "delete", feed_itemc, method: :delete,
										data: { confirm: "You sure?" },
										title: feed_itemc.content %>
	<% end %>
</li>

app/views/shared/_feedc.html.erb
<% if @feed_items.any? %>
	<ol class="calendars">
		<%= render partial: 'shared/feed_itemc', collection: @feed_items %>
	</ol>
	<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<table><tr>
<%= form_for(@micropost) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="field">
		<%= f.text_area :content %>
	</div>
	<td>
		<%= f.submit "つぶやく", class: "btn btn-large btn-primary" %>
	</td>
<% end %>
<td>
</td>
	<% start = Micropost.find_by(:user_id => current_user, :content => "start") %>
	<% stop = Micropost.find_by(:user_id => current_user, :content => "stop") %>
<% if start && stop %>
<%= form_for(@micropost) do |f| %>
	<% if start.created_at > stop.created_at %>
		<td>
		<%= f.hidden_field :content, :value => "stop" %>
		<%= f.submit "研究終わり", class: "btn btn-large btn-primary" %>
		</td>
	<% elsif start.created_at < stop.created_at %>
		<td>
		<%= f.hidden_field :content, :value => "start" %>
		<%= f.submit "研究開始", class: "btn btn-large btn-primary" %>
		</td>
	<% else %>
		<td>
		<%= f.hidden_field :content, :value => "start" %>
		<%= f.submit "研究開始", class: "btn btn-large btn-primary" %>	
		</td>
	<% end %>
<% end %>
<% elsif start %>
<%= form_for(@micropost) do |f| %>
	<td>
		<%= f.hidden_field :content, :value => "stop" %>
		<%= f.submit "研究終わり", class: "btn btn-large btn-primary" %>
		</td>
		<% end %>
<% else %>
<%= form_for(@micropost) do |f| %>
		<td>
		<%= f.hidden_field :content, :value => "start" %>
		<%= f.submit "研究開始", class: "btn btn-large btn-primary" %>	
		</td>
	<% end %>
<% end %>
</tr>
</table>


app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
	
	<a href="<%= following_user_path(@user) %>">
		<strong id="following" class="stat">
			<%= @user.followed_users.count %>
		</strong>
		following
	</a>
	<a href="<%= followers_user_path(@user) %>">
		<strong id="followers" class="stat">
			<%= @user.followers.count %>
		</strong>
		followers
	</a>

</div>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
	<%= gravatar_for current_user, size: 52 %>
</a>
<h1>
	<%= current_user.name %>
</h1>
<span>
	<%= link_to "プロフィール", current_user %>
</span>
<span>
	つぶやき<%= " " %><%= current_user.microposts.count %>
</span>