config/routes.rb
SampleApp2::Application.routes.draw do
  resources :users do
   member do
    get :following, :followers
   end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :calendars, only: [:destroy, :create, :new, :update]
  resources :relationships, only: [:create, :destroy]
  root 'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/login', to: 'sessions#new', via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'delete'
  match '/users', to: 'users#index', via: 'get'
  match '/sample', to: 'static_pages#micropost', via: 'get'
  match '/calendar/:year/:month/:day', to: 'calendars#calendar', via: 'get'
  match '/edit/:year/:month/:day', to: 'calendars#edit', via: 'get'
  match '/index', to: 'calendars#index', via: 'get'
  post '/calendars/:date' => 'calendars#calendar'
  post "static_pages/show" => "static_pages#show"
  post '/calendar/:date' => 'calendars#update'

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "卒研管理アプリケーション", root_path, id: "logo" %>
			<nav>
				<ul class="nav pull-right">
					
					<% if signed_in? %>
						<li><%= link_to "#{current_user.student_id} #{current_user.name}", root_path %></li>
						<li><%= link_to "プロフィール編集", edit_user_path(current_user) %></li>
						<li><%= link_to "ログアウト", logout_path, method: "delete" %></li>
					<% else %>
						<li><%= link_to "Home", root_path %></li>
						<li><%= link_to "ログイン", login_path %></li>
					<% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>卒研管理アプリケーション</title>
		<%= stylesheet_link_tag "application", media: "all",
								"data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |key, value| %>
				<div class="alert alert-<%= key %>"><%= value %></div>
			<% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
			<%#= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>